program MainRetail;

{%ToDo 'MainRetail.todo'}

uses          
  Forms,
  uPassword in 'uPassword.pas' {Password},
  uBrwUserType in 'uBrwUserType.pas' {brwUserType},
  uFrmUserType in 'uFrmUserType.pas' {brwFrmUserType},
  uBrwUser in 'uBrwUser.pas' {brwUser},
  uFrmUser in 'uFrmUser.pas' {brwFrmUser},
  uBrwCashRegister in 'uBrwCashRegister.pas' {brwCashRegister},
  uFrmCashRegister in 'uFrmCashRegister.pas' {brwFrmCashRegister},
  uBrwCashRegMov in 'uBrwCashRegMov.pas' {brwCashRegMov},
  uItemsCalc in 'uItemsCalc.pas' {frmItemsCalc},
  uFchParam in 'uFchParam.pas' {FchParameter},
  uBrwSpecialPrice in 'uBrwSpecialPrice.pas' {brwSpecialPrice},
  uBrwGroup in 'uBrwGroup.pas' {brwGroup},
  ubrwModel in 'ubrwModel.pas' {brwModel},
  uBrwStore in 'uBrwStore.pas' {brwStore},
  uFrmGroup in 'uFrmGroup.pas' {brwFrmGroup},
  uFrmNewBarCode in 'uFrmNewBarCode.pas' {FrmNewBarcode},
  uFrmSpecialPrice in 'uFrmSpecialPrice.pas' {brwFrmSpecialPrice},
  uFrmStore in 'uFrmStore.pas' {brwFrmStore},
  uBrwInventMovType in 'uBrwInventMovType.pas' {brwInventMovType},
  uFrmInventMovType in 'uFrmInventMovType.pas' {brwFrmInventMovType},
  uBrwSaleRequest in 'uBrwSaleRequest.pas' {brwSaleRequest},
  uFrmSaleRequest in 'uFrmSaleRequest.pas' {brwFrmRequest},
  uQueryInventory in 'uQueryInventory.pas' {QueryInventory},
  uBrwDeliverType in 'uBrwDeliverType.pas' {brwDeliverType},
  uFrmDeliverType in 'uFrmDeliverType.pas' {brwFrmDeliverType},
  uFrmParameter in 'uFrmParameter.pas' {FrmParameter},
  uPreSaleItem in 'uPreSaleItem.pas' {FrmPreSaleItem},
  uMakeSpcPrice in 'uMakeSpcPrice.pas' {FrmMakeSpcPrice},
  uTaxIsent in 'uTaxIsent.pas' {FrmTaxIsent},
  uFrmPO in 'PO\uFrmPO.pas' {FrmPO},
  uInvoice in 'uInvoice.pas' {FrmInvoice},
  uPreSaleReceive in 'uPreSaleReceive.pas' {PreSaleReceive},
  uPrinting in 'uPrinting.pas' {FrmPrinting},
  uBrwMidia in 'uBrwMidia.pas' {brwMidia},
  uFrmMidia in 'uFrmMidia.pas' {BrwFrmMidia},
  uBrwInvoice in 'uBrwInvoice.pas' {brwInvoice},
  uFchRepair in 'uFchRepair.pas' {FchRepair},
  uBrwInventoryMov in 'uBrwInventoryMov.pas' {brwInventoryMov},
  uFrmInventoryMov in 'uFrmInventoryMov.pas' {brwFrmInventoryMov},
  uEditPreSale in 'uEditPreSale.pas' {FrmEditPreSale},
  uNewSerial in 'uNewSerial.pas' {NewSerial},
  uSplitPreSale in 'uSplitPreSale.pas' {SplitPreSale},
  uNewFornecedor in 'uNewFornecedor.pas' {NewFornecedor},
  uFrmEstado in 'uFrmEstado.pas' {brwFrmEstado},
  uBrwEstado in 'uBrwEstado.pas' {brwEstado},
  uAskManager in 'uAskManager.pas' {FrmAskManager},
  uBrwPessoa in 'uBrwPessoa.pas' {BrwPessoa},
  uFchPessoa in 'uFchPessoa.pas' {FchPessoa},
  uBrwInventory in 'uBrwInventory.pas' {brwInventory},
  uCashRegManager in 'uCashRegManager.pas' {CashRegManager},
  uFchInventory in 'uFchInventory.pas' {FchInventory},
  uCashRegClose in 'uCashRegClose.pas' {CashRegClose},
  uBrwTouristGroup in 'uBrwTouristGroup.pas' {brwTouristGroup},
  uFchTouristGroup in 'uFchTouristGroup.pas' {FchTouristGroup},
  uFchTrajeto in 'uFchTrajeto.pas' {FchTrajeto},
  uFchCost in 'uFchCost.pas' {FchCost},
  uFchCostType in 'uFchCostType.pas' {FchCostType},
  uFchModel in 'uFchModel.pas' {FchModel},
  uFchTipoComissionado in 'uFchTipoComissionado.pas' {FchTipoComissionado},
  uBrwTrajeto in 'uBrwTrajeto.pas' {BrwTrajeto},
  uBrwCostType in 'uBrwCostType.pas' {BrwCostType},
  uAddTrajeto in 'uAddTrajeto.pas' {AddTrajeto},
  uFchAcertaTourGroup in 'uFchAcertaTourGroup.pas' {FchAcertaTourGroup},
  uFrmPagaGuia in 'uFrmPagaGuia.pas' {FrmPagaGuia},
  uFrmPagaAgencia in 'uFrmPagaAgencia.pas' {FrmPagaAgencia},
  uFrmChangeTourGroup in 'uFrmChangeTourGroup.pas' {FrmChangeTourGroup},
  uPrintReceipt in 'uPrintReceipt.pas' {PrintReceipt},
  uPrintCashReg in 'uPrintCashReg.pas' {PrintCashReg},
  uCashRegWidraw in 'uCashRegWidraw.pas' {CashRegWidraw},
  uCashRegPetty in 'uCashRegPetty.pas' {CashRegPetty},
  uFchCashRegMov in 'uFchCashRegMov.pas' {FchCashRegMov},
  uFchCashRegMovConf in 'uFchCashRegMovConf.pas' {FchCashRegMovConf},
  uCalcCash in 'uCalcCash.pas' {CalcCash},
  uModelAdjustQty in 'uModelAdjustQty.pas' {ModelAdjustQty},
  uPrintGuideReceipt in 'uPrintGuideReceipt.pas' {PrintGuideReceipt},
  uCashRegTotal in 'uCashRegTotal.pas' {CashRegTotal},
  uBrwHotel in 'uBrwHotel.pas' {brwHotel},
  uFchHotel in 'uFchHotel.pas' {FchHotel},
  uFrmPagaOther in 'uFrmPagaOther.pas' {FrmPagaOther},
  uFrmPagaVendedor in 'uFrmPagaVendedor.pas' {FrmPagaVendedor},
  uCashRegEnvelop in 'uCashRegEnvelop.pas' {CashRegEnvelop},
  uInvoicePayment in 'uInvoicePayment.pas' {InvoicePayment},
  uPrintComissReceipt in 'uPrintComissReceipt.pas' {PrintComissReceipt},
  uBrwModelTransf in 'uBrwModelTransf.pas' {brwModelTransf},
  uNewModelTransf in 'uNewModelTransf.pas' {FrmNewModelTransf},
  uPrintRepairStoreReceipt in 'uPrintRepairStoreReceipt.pas' {PrintRepairStoreReceipt},
  uSetDelPreSaleDate in 'uSetDelPreSaleDate.pas' {SetDelPreSaleDate},
  uMenuItem in 'uMenuItem.pas' {FrmMenuItem},
  uTourGroupResult in 'uTourGroupResult.pas' {TourGroupResult},
  uFrmInventoryCount in 'uFrmInventoryCount.pas' {FrmInventoryCount},
  uInventoryCleanUp in 'uInventoryCleanUp.pas' {InventoryCleanUp},
  ubrwCotation in 'ubrwCotation.pas' {brwCotation},
  uBrwRepairInv in 'uBrwRepairInv.pas' {brwRepairInv},
  uBrwRepairCli in 'uBrwRepairCli.pas' {brwRepairCli},
  uFrmTransferData in 'uFrmTransferData.pas' {FrmTransferData},
  uFrmHourResult in 'uFrmHourResult.pas' {FrmHourResult},
  uPrintRepairCliReceipt in 'uPrintRepairCliReceipt.pas' {PrintRepairCliReceipt},
  uWaitForm in 'uWaitForm.pas' {WaitForm},
  uFchCotation in 'uFchCotation.pas' {FchCotation},
  uFrmBarcodeSearch in 'uFrmBarcodeSearch.pas' {FrmBarcodeSearch},
  UBrwFrmPais in 'UBrwFrmPais.pas' {brwFrmPais},
  uCreateFile in 'uCreateFile.pas' {FrmCreateFile},
  uBrwMeioPag in 'uBrwMeioPag.pas' {BrwMeioPag},
  uFchMeioPag in 'uFchMeioPag.pas' {FchMeioPag},
  uNewPreSales in 'uNewPreSales.pas' {FrmNewPreSales},
  UBrwTaxCategory in 'UBrwTaxCategory.pas' {BrwTaxCategory},
  uFchTaxCategory in 'uFchTaxCategory.pas' {FchTaxCategory},
  uMediaResults in 'uMediaResults.pas' {MediaResults},
  uFrmTimeControlPrint in 'uFrmTimeControlPrint.pas' {frmTimeControlPrint},
  uFrmTimeControlUpdate in 'uFrmTimeControlUpdate.pas' {FrmTimeControlUpdate},
  ubrwFrmColor in 'ubrwFrmColor.pas' {brwFrmColor},
  ubrwSize in 'ubrwSize.pas' {brwSize},
  ubrwFrmSize in 'ubrwFrmSize.pas' {brwFrmSize},
  ubrwPurchase in 'Purchase\ubrwPurchase.pas' {brwPurchase},
  uBrwNewPO in 'PO\uBrwNewPO.pas' {BrwNewPO},
  uFchPurchaseItemNewBarCode in 'Purchase\uFchPurchaseItemNewBarCode.pas' {FchPurchaseItemNewBarCode},
  uFrmAddGift in 'uFrmAddGift.pas' {FrmAddGift},
  uFchUnidade in 'uFchUnidade.pas' {FchUnidade},
  uValidSenha in 'uValidSenha.pas' {ValidSenha},
  uMovePreSale in 'uMovePreSale.pas' {MovePreSale},
  uFrmModelAddSize in 'uFrmModelAddSize.pas' {FrmModelAddSize},
  uFrmModelAddColor in 'uFrmModelAddColor.pas' {FrmModelAddColor},
  uFrmFastSale in 'uFrmFastSale.pas' {FrmFastSale},
  uFrmMovNotes in 'uFrmMovNotes.pas' {FrmMovNotes},
  uFrmModelPriceAdj in 'uFrmModelPriceAdj.pas' {frmModelPriceAdj},
  uFrameSendContact in 'uFrameSendContact.pas' {FrameSendContact: TFrame},
  uFrmInvResetView in 'uFrmInvResetView.pas' {FrmInvResetView},
  uModuleConfig in 'uModuleConfig.pas',
  PaiDeTodos in 'FrmParents\PAIDETODOS.pas' {FrmParent},
  PaideTodosGeral in 'FrmParents\PaideTodosGeral.pas' {FrmParentAll},
  uFileFunctions in '..\RepositoryD7\uFileFunctions.pas',
  PaiDeBrowses in 'FrmParents\PaiDeBrowses.pas' {brwParent},
  PaiDeFichas in 'FrmParents\PaiDeFichas.pas' {brwFrmParent},
  PaideFichaTab in 'FrmParents\PaideFichaTab.pas' {brwFrmTabParent},
  PaideTreeBrowse in 'FrmParents\PaideTreeBrowse.pas' {brwTreeParent},
  uMsgBox in '..\RepositoryD7\uMsgBox.pas' {FrmMsgBox},
  PaideTreeItemBrowse in 'FrmParents\PaideTreeItemBrowse.pas' {brwTreeItemParent},
  PaiDeFichasBrowse in 'FrmParents\PaiDeFichasBrowse.pas' {brwFrmParentBrw},
  ExitQue in 'ExitQue.pas' {ExitQuery},
  uDialogParent in 'FrmParents\uDialogParent.pas' {DialogParent},
  uDMGlobal in '..\RepositoryD7\uDMGlobal.pas' {DMGlobal: TDataModule},
  uWebFunctions in '..\RepositoryD7\uWebFunctions.pas',
  uFrmExport in 'uFrmExport.pas' {FrmExport},
  uFrmTimeControl in 'uFrmTimeControl.pas' {FrmTimeControl},
  PaiDeForms in 'FrmParents\PaiDeForms.pas' {FrmParentForms},
  uMsgConstant in '..\RepositoryD7\uMsgConstant.pas' {FrmMsgConstant},
  uFrmFastSaleGroucery in 'uFrmFastSaleGroucery.pas' {FrmFastSaleGrocery},
  uPrint in '..\RepositoryD7\uPrint.pas',
  uFrmBarcodePrint in 'uFrmBarcodePrint.pas' {FrmBarcodePrint},
  uFrmModelAddSizeColor in 'uFrmModelAddSizeColor.pas' {FrmModelAddSizeColor},
  uFrmMemo in 'uFrmMemo.pas' {FrmMemo},
  PaidePrinter in 'FrmParents\PaidePrinter.pas' {FrmParentPrint},
  uFrmImportPO in 'PO\uFrmImportPO.pas' {FrmImportPO},
  uSystemConst in '..\RepositoryD7\uSystemConst.pas',
  uDMParent in '..\RepositoryD7\uDMParent.pas' {DMParent: TDataModule},
  MenuPrincipal in 'MenuPrincipal.pas' {MainMenu},
  uDM in 'uDM.pas' {DM: TDataModule},
  uFrmSystemInfo in 'uFrmSystemInfo.pas' {FrmSystemInfo},
  uSystemObj in '..\RepositoryD7\uSystemObj.pas',
  uUserObj in '..\RepositoryD7\uUserObj.pas',
  uSQLObj in '..\RepositoryD7\uSQLObj.pas',
  uParentClass in '..\RepositoryD7\uParentClass.pas',
  uStringObj in '..\RepositoryD7\uStringObj.pas',
  uBrwColor in 'uBrwColor.pas' {brwColor},
  uFchPurchase in 'Purchase\uFchPurchase.pas' {FchPurchase},
  uFchPurchaseItem in 'Purchase\uFchPurchaseItem.pas' {FchPurchaseItem},
  uFchTransferModel in 'uFchTransferModel.pas' {FchTransferModel},
  uFchTranfModelItem in 'uFchTranfModelItem.pas' {FchTranfModelItem},
  uParentSub in '..\RepositoryD7\uParentSub.pas' {ParentSub},
  uSubGridLayout in 'uSubGridLayout.pas' {SubGridLayout},
  uSubStoreQty in 'uSubStoreQty.pas' {SubStoreQty},
  ufrmLanguage in '..\RepositoryD7\ufrmLanguage.pas' {frmLanguage},
  ufrmLanguageMR in 'ufrmLanguageMR.pas' {frmLanguageMR},
  uSubModelDetail in 'uSubModelDetail.pas' {SubModelDetail},
  uSubPurchaseHistory in 'uSubPurchaseHistory.pas' {SubPurchaseHistory},
  uSubSaleHistory in 'uSubSaleHistory.pas' {SubSaleHistory},
  uSubMovHistory in 'uSubMovHistory.pas' {SubMovHistory},
  uSubMovTotal in 'uSubMovTotal.pas' {SubMovTotal},
  uSubOrderHistory in 'uSubOrderHistory.pas' {SubOrderHistory},
  uSubVendorHistory in 'uSubVendorHistory.pas' {SubVendorHistory},
  uSubSendFax in 'uSubSendFax.pas' {SubSendFax},
  uSubRequest in 'uSubRequest.pas' {SubRequest},
  uFrmSerialNumber in 'uFrmSerialNumber.pas' {FrmSerialNumber},
  uSubTicketInfo in 'uSubTicketInfo.pas' {SubTicketInfo},
  uFrmPreviewTicket in 'uFrmPreviewTicket.pas' {FrmPreviewTicket},
  uFrmPOSFunctions in 'uFrmPOSFunctions.pas' {FrmPOSFunctions},
  uCashRegOpen in 'uCashRegOpen.pas' {CashRegOpen},
  ufrmServerInfo in '..\RepositoryD7\ufrmServerInfo.pas' {FrmServerInfo},
  uTranslateScript in '..\RepositoryD7\uTranslateScript.pas',
  uFrmLicenseKey in '..\RepositoryD7\uFrmLicenseKey.pas' {FrmLicenseKey},
  uSubBestSeller in 'uSubBestSeller.pas' {SubBestSeller},
  uFrmPayPartial in 'uFrmPayPartial.pas' {FrmPayPartial},
  uSubModelImage in 'uSubModelImage.pas' {SubModelImage},
  uFrmModelPicture in 'uFrmModelPicture.pas' {FrmModelPicture},
  uSubHoldPayments in 'uSubHoldPayments.pas' {SubHoldPayments},
  uFrmZipSearch in '..\RepositoryD7\uFrmZipSearch.pas' {FrmZipSearch},
  uSubInvAccessory in 'uSubInvAccessory.pas' {SubInvAccessory},
  uFrmSERASA in 'uFrmSERASA.pas' {FrmSERASA},
  uSubSaleConsult in 'uSubSaleConsult.pas' {SubSaleConsult},
  uFrmHistory in 'uFrmHistory.pas' {FrmHistory},
  uFrmSaleConsult in 'uFrmSaleConsult.pas' {FrmSaleConsult},
  uCashregCloseConfer in 'uCashregCloseConfer.pas' {CashregCloseConfer},
  uFrmHistoryManage in 'uFrmHistoryManage.pas' {FrmHistoryManage},
  uSubShortCuts in 'uSubShortCuts.pas' {SubShortCuts},
  uFchHistoryType in 'uFchHistoryType.pas' {FchHistoryType},
  uFrmConsultHold in 'uFrmConsultHold.pas' {FrmConsultHold},
  uSubCustomerInfo in 'uSubCustomerInfo.pas' {SubCustomerInfo},
  uFrmEstimated in 'uFrmEstimated.pas' {FrmEstimated},
  uFrmEstimatedNew in 'uFrmEstimatedNew.pas' {FrmEstimatedNew},
  uFrmCreditPay in 'uFrmCreditPay.pas' {FrmCreditPay},
  uFrmEstimatedItemNew in 'uFrmEstimatedItemNew.pas' {FrmEstimatedItemNew},
  uSubModelWebInfo in 'uSubModelWebInfo.pas' {SubModelWebInfo},
  uFrmCustomerAddCredit in 'uFrmCustomerAddCredit.pas' {FrmCustomerAddCredit},
  uFrmEstimatedPrint in 'uFrmEstimatedPrint.pas' {FrmEstimatedPrint},
  uSubModelWarranty in 'uSubModelWarranty.pas' {SubModelWarranty},
  uSubCalcSaleTax in 'uSubCalcSaleTax.pas' {SubCalcSaleTax},
  uSubCalcPurchaseTax in 'uSubCalcPurchaseTax.pas' {SubCalcPurchaseTax},
  uBrwSizeColorGroup in 'uBrwSizeColorGroup.pas' {brwSizeColorGroup},
  uBrwFrmSizeColorGroup in 'uBrwFrmSizeColorGroup.pas' {brwFrmSizeColorGroup},
  uFrmPrintDelivery in 'uFrmPrintDelivery.pas' {FrmPrintDelivery},
  uFchPetSpecies in 'uFchPetSpecies.pas' {FchPetSpecies},
  uFchPet in 'uFchPet.pas' {FchPet},
  uFchPetPorte in 'uFchPetPorte.pas' {FchPetPorte},
  uFchPetRace in 'uFchPetRace.pas' {FchPetRace},
  uFrmJoinHold in 'uFrmJoinHold.pas' {FrmJoinHold},
  uFrmPrintDeliveryList in 'uFrmPrintDeliveryList.pas' {FrmPrintDeliveryList},
  uFrmInventoryList in 'uFrmInventoryList.pas' {FrmInventoryList},
  uFrmSaleItemTax in 'uFrmSaleItemTax.pas' {FrmSaleItemTax},
  uFrmFastSale2 in 'uFrmFastSale2.pas' {FrmFastSale2},
  uFrmPrintTranfer in 'uFrmPrintTranfer.pas' {FrmPrintTransfer},
  uFrmTransferImport in 'uFrmTransferImport.pas' {FrmTransferImport},
  uNewFornecedorCode in 'uNewFornecedorCode.pas' {NewFornecedorCode},
  uFrmPreSaleItemDiscount in 'uFrmPreSaleItemDiscount.pas' {FrmPreSaleItemDiscount},
  uFrmImportEstimated in 'uFrmImportEstimated.pas' {FrmImportEstimated},
  uFrmUserMessager in 'uFrmUserMessager.pas' {FrmUserMessager},
  uFrmUserMessageSend in 'uFrmUserMessageSend.pas' {FrmUserMessageSend},
  uFrmUserMessageUserList in 'uFrmUserMessageUserList.pas' {FrmUserMessageUserList},
  uFrmNewMessage in 'uFrmNewMessage.pas' {FrmNewMessage},
  uFchRound in 'uFchRound.pas' {FchRound},
  uBrwRound in 'uBrwRound.pas' {brwRound},
  uFchRoundRange in 'uFchRoundRange.pas' {FchRoundRange},
  uFrmPCCSwipeCard in '..\RepositoryD7\uFrmPCCSwipeCard.pas' {frmPCCSwipeCard},
  uBrwMargem in 'uBrwMargem.pas' {brwMargem},
  uFchMargem in 'uFchMargem.pas' {FchMargem},
  uFchMargemRange in 'uFchMargemRange.pas' {FchMargemRange},
  ufrmPCVoid in 'ufrmPCVoid.pas' {frmPCVoid},
  uBrwModelGroup in 'uBrwModelGroup.pas' {brwModelGroup},
  uFrmModelGroup in 'uFrmModelGroup.pas' {brwFrmModelGroup},
  uBrwModelSubGroup in 'uBrwModelSubGroup.pas' {brwModelSubGroup},
  uFrmModelSubGroup in 'uFrmModelSubGroup.pas' {brwFrmModelSubGroup},
  uFrmPricingSetup in 'uFrmPricingSetup.pas' {FrmPricingSetup},
  uFrmMarginTable in 'uFrmMarginTable.pas' {FrmMarginTable},
  uFrmAddItemCommission in 'uFrmAddItemCommission.pas' {FrmAddItemCommission},
  uFrmPCCWaitTransaction in 'uFrmPCCWaitTransaction.pas' {frmPCCWaitTransaction},
  uFrmMainPOS in 'uFrmMainPOS.pas' {FrmMainPOS},
  uFrmParentSales in 'Sales\uFrmParentSales.pas' {FrmParentSales},
  uSubModelFeatures in 'uSubModelFeatures.pas' {SubModelFeatures},
  uSaleItem in 'Sales\uSaleItem.pas',
  uInvoiceInfo in 'Sales\uInvoiceInfo.pas',
  uFrmParentSaleFull in 'Sales\uFrmParentSaleFull.pas' {FrmParentSaleFull},
  uFrmParentSaleFast in 'Sales\uFrmParentSaleFast.pas' {FrmParentSaleFast},
  uFrmMarginTableApply in 'uFrmMarginTableApply.pas' {FrmMarginTableApply},
  uDMCloseCount in 'Inventory\uDMCloseCount.pas' {DMCloseCount: TDataModule},
  uFrmMainPOSInfo in 'uFrmMainPOSInfo.pas' {FrmMainPOSInfo},
  uFrmSearchCustomer in 'uFrmSearchCustomer.pas' {FrmSearchCustomer},
  uFrmAdjustMinMax in 'uFrmAdjustMinMax.pas' {FrmAdjustMinMax},
  uFrmAdjustMinMaxAll in 'uFrmAdjustMinMaxAll.pas' {FrmAdjustMinMaxAll},
  uFrmInventoryConfig in 'uFrmInventoryConfig.pas' {FrmInventoryConfig},
  uDMInventory in 'Inventory\uDMInventory.pas' {DMInventory: TDataModule},
  uFrmNewPOTransfer in 'PO\uFrmNewPOTransfer.pas' {FrmNewPOTransfer},
  uFrmNewPOTransferConsult in 'PO\uFrmNewPOTransferConsult.pas' {FrmNewPOTransferConsult},
  uFrmNewPOAuto in 'PO\uFrmNewPOAuto.pas' {FrmNewPOAuto},
  uFrmNewMultPO in 'PO\uFrmNewMultPO.pas' {FrmNewMultPO},
  uFrmNewPOQuickEntry in 'PO\uFrmNewPOQuickEntry.pas' {FrmNewPOQuickEntry},
  uFrmPurchaseItemQuickEntry in 'Purchase\uFrmPurchaseItemQuickEntry.pas' {FrmPurchaseItemQuickEntry},
  uFrmPrintPO in 'PO\uFrmPrintPO.pas' {FrmPrintPO},
  uFchCustomerType in 'uFchCustomerType.pas' {FchCustomerType},
  uFchStoreVendorAccount in 'uFchStoreVendorAccount.pas' {FchStoreVendorAccount},
  uFrmMarginTableUpdate in 'uFrmMarginTableUpdate.pas' {FrmMarginTableUpdate},
  uFrmInvoiceRefund in 'uFrmInvoiceRefund.pas' {FrmInvoiceRefund},
  uBrwPromo in 'uBrwPromo.pas' {brwPromo},
  uFchPromo in 'uFchPromo.pas' {FchPromo},
  uNewPersonType in 'uNewPersonType.pas' {NewPersonType},
  uFrmPromoPrizeItem in 'uFrmPromoPrizeItem.pas' {FrmPromoPrizeItem},
  uFrmPromoItem in 'uFrmPromoItem.pas' {FrmPromoItem},
  uFrmAccountCard in 'uFrmAccountCard.pas' {FrmAccountCard},
  uFrmAccountAddAmount in 'uFrmAccountAddAmount.pas' {FrmAccountAddAmount},
  uFrmInventoryAdjust in 'uFrmInventoryAdjust.pas' {FrmInventoryAdjust},
  uFchDefectType in 'uFchDefectType.pas' {FchDefectType},
  uFchDepartment in 'Inventory\uFchDepartment.pas' {FchDepartment},
  uFrmModelDepartment in 'Inventory\uFrmModelDepartment.pas' {FrmModelDepartment},
  uSelectDepartment in 'uSelectDepartment.pas' {SelectDepartment},
  uNewModelReceipt in 'uNewModelReceipt.pas' {NewModelReceipt},
  uRBFunction in '..\RepositoryD7\uRBFunction.pas',
  uContentClasses in 'Inventory\uContentClasses.pas',
  uFrmPromoItemList in 'uFrmPromoItemList.pas' {FrmPromoItemList},
  uFchInventoryReason in 'uFchInventoryReason.pas' {FchInventoryReason},
  uDMCalcPrice in '..\RepositoryD7\uDMCalcPrice.pas' {DMCalcPrice: TDataModule},
  uFrmTeleMarketing in 'uFrmTeleMarketing.pas' {FrmTeleMarketing},
  uFrmPessoaHistory in 'uFrmPessoaHistory.pas' {FrmPessoaHistory},
  uFchPessoaHistoryType in 'uFchPessoaHistoryType.pas' {FchPessoaHistoryType},
  uFrmPessoaHistoryTypeResult in 'uFrmPessoaHistoryTypeResult.pas' {FrmPessoaHistoryTypeResult},
  uFrmDrawerKickLog in 'uFrmDrawerKickLog.pas' {FrmDrawerKickLog},
  uFrmTelemarketingFilter in 'uFrmTelemarketingFilter.pas' {FrmTelemarketingFilter},
  uFrmImportTransferNumber in 'uFrmImportTransferNumber.pas' {FrmImportTransferNumber},
  uCDSFunctions in '..\RepositoryD7\uCDSFunctions.pas',
  uFrmParentQuickEntryList in 'Inventory\uFrmParentQuickEntryList.pas' {FrmParentQuickEntryList},
  uDMCalcTax in '..\RepositoryD7\uDMCalcTax.pas' {DMCalcTax: TDataModule},
  uFrmQuickEntryListInsert in 'Inventory\uFrmQuickEntryListInsert.pas' {FrmQuickEntryListInsert},
  uFrmQuickEntryListUpdate in 'Inventory\uFrmQuickEntryListUpdate.pas' {FrmQuickEntryListUpdate},
  uFrmAskPrice in 'uFrmAskPrice.pas' {FrmAskPrice},
  uFrmEmailBuilder in 'uFrmEmailBuilder.pas' {FrmEmailBuilder},
  uFrmPrintCustomerLabel in 'uFrmPrintCustomerLabel.pas' {FrmPrintCustomerLabel},
  uBrwRebateCalendar in 'uBrwRebateCalendar.pas' {brwRebateCalendar},
  uBonusBucks in 'Sales\uBonusBucks.pas',
  uFchRebateCalendar in 'uFchRebateCalendar.pas' {FchRebateCalendar},
  uFrmBonusBucks in 'uFrmBonusBucks.pas' {FrmParent1},
  uFrmSelectRebateCalendar in 'uFrmSelectRebateCalendar.pas' {FrmSelectRebateCalendar},
  uFrmBonusBuckPercentAll in 'uFrmBonusBuckPercentAll.pas' {FrmBonusBucksPercentAll},
  uFrmPromotionSetup in 'uFrmPromotionSetup.pas' {FrmPromotionSetup},
  uSubRupture in 'Inventory\uSubRupture.pas' {SubRupture},
  uFrmAddKitItems in 'uFrmAddKitItems.pas' {FrmAddKitItems},
  uPayment in 'Sales\uPayment.pas',
  uSaleReceive in 'Sales\uSaleReceive.pas',
  uFrmPaymentReceive in 'Sales\uFrmPaymentReceive.pas' {FrmPaymentReceive},
  uPaymentBonusBucks in 'Sales\uPaymentBonusBucks.pas',
  uMRPCCharge in 'Sales\uMRPCCharge.pas',
  uFrmListPayments in 'Sales\uFrmListPayments.pas' {FrmListPayments},
  uPaymentCheck in 'Sales\uPaymentCheck.pas',
  uPaymentOther in 'Sales\uPaymentOther.pas',
  uPaymentGiftCard in 'Sales\uPaymentGiftCard.pas',
  uPaymentStoreCredit in 'Sales\uPaymentStoreCredit.pas',
  uFrmGiftCardNumber in 'Sales\uFrmGiftCardNumber.pas' {FrmGiftCardNumber},
  uFrmCashBackValue in 'Sales\uFrmCashBackValue.pas' {FrmCashBackValue},
  uFchCashRegLogReason in 'uFchCashRegLogReason.pas' {FchCashRegLogReason},
  uFrmListVendor in 'uFrmListVendor.pas' {FrmListVendor},
  uFrmShippingDistrubSale in 'Sales\uFrmShippingDistrubSale.pas' {FrmShippingDistrubSale},
  uFchPessoaAddress in 'uFchPessoaAddress.pas' {FchPessoaAddress},
  uFrmPrintShippingOption in 'uFrmPrintShippingOption.pas' {FrmPrintShippingOption},
  uFrmApplyItemTax in 'uFrmApplyItemTax.pas' {FrmApplyItemTax},
  uFrmTrackPackage in 'uFrmTrackPackage.pas' {FrmTrackPackage},
  uFrmAskSalesPerson in 'uFrmAskSalesPerson.pas' {FrmAskSalesPerson},
  uFrmAddItems in 'uFrmAddItems.pas' {FrmAddItems},
  uFrmCountInventoryConfig in 'uFrmCountInventoryConfig.pas' {FrmCountInventoryConfig},
  uFrmPurchaseCalcFreight in 'Purchase\uFrmPurchaseCalcFreight.pas' {FrmPurchaseCalcFreight},
  uSubStorePrice in 'uSubStorePrice.pas' {SubStorePrice},
  uFrmAddInvoiceOBS in 'Sales\uFrmAddInvoiceOBS.pas' {FrmAddInvoiceOBS},
  uFrmNewInvoiceOBS in 'Sales\uFrmNewInvoiceOBS.pas' {FrmNewInvoiceOBS},
  uFrmModelPrice in 'Inventory\uFrmModelPrice.pas' {FrmModelPrice},
  uFrmStorePrice in 'Inventory\uFrmStorePrice.pas' {FrmStorePrice},
  uFrmDescriptionPrice in 'uFrmDescriptionPrice.pas' {FrmDescriptionPrice},
  uFrmChoosePrice in 'Sales\uFrmChoosePrice.pas' {FrmChoosePrice},
  ubrwMovDocument in 'Sales\ubrwMovDocument.pas' {brwMovDocument},
  uFchMovDocument in 'Sales\uFchMovDocument.pas' {FchMovDocument},
  uFchDocumentType in 'Sales\uFchDocumentType.pas' {FchDocumentType},
  uFrmEnterMovDocumet in 'Sales\uFrmEnterMovDocumet.pas' {FrmEnterMovDocumet},
  uPetCenterCli in '..\RepositoryD7\uPetCenterCli.pas',
  uFrmPetSearch in 'uFrmPetSearch.pas' {FrmPetSearch},
  uFrmPrintRepair in 'uFrmPrintRepair.pas' {FrmPrintRepair},
  uFrmPrintReceiving in 'Purchase\uFrmPrintReceiving.pas' {FrmPrintReceiving},
  uFrmAssociateDepartment in 'Inventory\uFrmAssociateDepartment.pas' {FrmAssociateDepartment},
  uSaleFinalize in 'Sales\uSaleFinalize.pas',
  uFchCFOP in 'uFchCFOP.pas' {FchCFOP},
  uFrmServiceOrderFch in 'ServiceOrder\uFrmServiceOrderFch.pas' {FrmServiceOrderFch},
  uDMServiceOrder in 'ServiceOrder\uDMServiceOrder.pas' {DMServiceOrder: TDataModule},
  uFchSOCustomerProduct in 'ServiceOrder\uFchSOCustomerProduct.pas' {FchSOCustomerProduct},
  uFchSOStatus in 'ServiceOrder\uFchSOStatus.pas' {FchSOStatus},
  uFrmServiceOrder in 'ServiceOrder\uFrmServiceOrder.pas' {FrmServiceOrder},
  uFrmSearchSOItem in 'ServiceOrder\uFrmSearchSOItem.pas' {FrmSearchSOItem},
  uFrmServiceOrderSearch in 'ServiceOrder\uFrmServiceOrderSearch.pas' {FrmServiceOrderSearch},
  uFrmServiceOrderPrint in 'ServiceOrder\uFrmServiceOrderPrint.pas' {FrmServiceOrderPrint},
  uDocumentInfo in 'uDocumentInfo.pas',
  uServiceOrderFinalize in 'ServiceOrder\uServiceOrderFinalize.pas',
  uFrmEntityValidation in 'uFrmEntityValidation.pas' {FrmEntityValidation},
  uPaymentStoreAccount in 'Sales\uPaymentStoreAccount.pas',
  uFrmStoreAccount in 'Sales\uFrmStoreAccount.pas' {FrmStoreAccount},
  uFrmPrintStoreAccount in 'uFrmPrintStoreAccount.pas' {FrmPrintStoreAccount},
  uFrmExportScaleItem in 'uFrmExportScaleItem.pas' {FrmExportScaleItem},
  uFrmEstimatedInfo in 'uFrmEstimatedInfo.pas' {FrmEstimatedInfo},
  uFrmMergePO in 'PO\uFrmMergePO.pas' {FrmMergePO},
  uFrmVerifyPO in 'PO\uFrmVerifyPO.pas' {FrmVerifyPO},
  uFrmBarcodePrintSingle in 'uFrmBarcodePrintSingle.pas' {FrmBarcodePrintSingle},
  tBarcodePrint in 'tBarcodePrint.pas',
  uFchRamoAtividade in 'uFchRamoAtividade.pas' {FchRamoAtividade},
  uFrmServiceOrderDiscount in 'ServiceOrder\uFrmServiceOrderDiscount.pas' {FrmServiceOrderDiscount},
  uFchLot in 'Inventory\uFchLot.pas' {FchLot},
  uFrmAdjustLot in 'uFrmAdjustLot.pas' {FrmAdjustLot},
  uCreditCardFunction in '..\RepositoryD7\uCreditCardFunction.pas',
  uFrmPrintBoleto in 'uFrmPrintBoleto.pas' {FrmPrintBoleto},
  uFchNCM in 'uFchNCM.pas' {FchNCM},
  uFchMunicipio in 'uFchMunicipio.pas' {FchMunicipio},
  uFrmModelStateTax in 'uFrmModelStateTax.pas' {FrmModelStateTax},
  uFchNutrition in 'uFchNutrition.pas' {FchNutrition},
  uFrmAddNutrition in 'uFrmAddNutrition.pas' {FrmAddNutrition},
  ufrmModelAdd in 'Inventory\ufrmModelAdd.pas' {frmModelAdd},
  uFrmModelQuickEntry in 'Inventory\uFrmModelQuickEntry.pas' {FrmModelQuickEntry},
  ufrmListOpenPOs in 'ufrmListOpenPOs.pas' {frmListOPenPOs},
  MRPuppySettings in 'MRPuppySettings.pas' {frmPuppySetting},
  MRpuppyIntegrationCls in 'MRpuppyIntegrationCls.pas',
  MsTask in '..\MainRetail_Wizard\MsTask.pas',
  MsTaskUtils in '..\MainRetail_Wizard\MsTaskUtils.pas',
  uPCCIntegration in '..\LibD7\uPCCIntegration.pas',
  frmCardNumberDialogView in 'frmCardNumberDialogView.pas' {CardNumberDlgView},
  frmSerialNumberDialogView in 'frmSerialNumberDialogView.pas' {frmSerialDgView},
  ufrmSerialNumberHistory in 'ufrmSerialNumberHistory.pas' {viewSerialNumberHistory},
  ufrmPurchaseBarcodeMessage in 'Purchase\ufrmPurchaseBarcodeMessage.pas' {frmPurchaseBarcodeMessage},
  SelectCorporateView in 'SelectCorporateView.pas' {dlgSelectCorpView},
  StoreCls in 'StoreCls.pas',
  SelectCorpCmd in 'SelectCorpCmd.pas',
  StoreDAO in 'StoreDAO.pas',
  SysRegistryDAO in 'SysRegistryDAO.pas',
  StoreSysRegistryCls in 'StoreSysRegistryCls.pas',
  clsInfoCashSale in 'clsInfoCashSale.pas',
  PromoDiscountInterface in 'Sales\Promo\PromoDiscountInterface.pas',
  PromoDiscountQtyClass in 'Sales\Promo\PromoDiscountQtyClass.pas',
  PromoDiscountAmountClass in 'Sales\Promo\PromoDiscountAmountClass.pas',
  PromoClass in 'Sales\Promo\PromoClass.pas',
  PromoConfigClass in 'Sales\Promo\PromoConfigClass.pas',
  PromoDiscountPercentClass in 'Sales\Promo\PromoDiscountPercentClass.pas',
  PromoDiscountSaleTotalClass in 'Sales\Promo\PromoDiscountSaleTotalClass.pas',
  PromoSaleClass in 'Sales\Promo\PromoSaleClass.pas',
  PromoCouponClass in 'Sales\Promo\PromoCouponClass.pas',
  PromoFreqBuyerClass in 'Sales\Promo\PromoFreqBuyerClass.pas',
  PromoLoyaltyClass in 'Sales\Promo\PromoLoyaltyClass.pas',
  PromoItemClass in 'Sales\Promo\PromoItemClass.pas',
  PromoItemInterface in 'Sales\Promo\PromoItemInterface.pas',
  PromoFactoryClass in 'Sales\Promo\PromoFactoryClass.pas',
  PromoDiscountFactoryClass in 'Sales\Promo\PromoDiscountFactoryClass.pas',
  MainPromoClass in 'Sales\Promo\MainPromoClass.pas',
  SendToVendorView in 'SendToVendorView.pas' {frmSendToVendorView},
  uFrmPromoControl in 'Sales\uFrmPromoControl.pas' {FrmPromoControl},
  AddTagModelView in 'Sales\AddTagModelView.pas' {frmAddTagModel},
  uFrmNewPO in 'PO\uFrmNewPO.pas' {frmNewPO},
  ItemPurchaseModel in 'PO\ItemPurchaseModel.pas',
  PromoDAO in 'Sales\Promo\PromoDAO.pas',
  PromoDTO in 'Sales\Promo\PromoDTO.pas',
  TagView in 'TagView.pas' {frmTagView},
  TagViewEdit in 'TagViewEdit.pas' {frmTagViewEdit},
  uCCMercuryIntegration in '..\LibD7\uCCMercuryIntegration.pas',
  PrintReceiptDeclinedView in 'PrintReceiptDeclinedView.pas',
  uMRPinPad in 'Sales\uMRPinPad.pas',
  uPaymentCard in 'Sales\uPaymentCard .pas',
  EMVAskingPopUp in 'Sales\EMVAskingPopUp.pas' {viewEMVAsking},
  AdjustQtyReasonView in 'Inventory\AdjustQtyReasonView.pas' {vwAdjustReason},
  AdjustReasonCls in 'Inventory\AdjustReasonCls.pas',
  AdjustQtyReasonUpsertView in 'Inventory\AdjustQtyReasonUpsertView.pas' {vwAdjustQtyReasonUpsert},
  PromoHandleConflict in 'Sales\Promo\PromoHandleConflict.pas',
  ViewPromoConflict in 'Sales\Promo\ViewPromoConflict.pas' {vwPromoConflict},
  BogoPromoCls in 'BogoPromoCls.pas';

{$R *.RES}

begin
  Application.Initialize;
  // amfsouza 11.04.2011 - was MainRetail 4
  Application.Title := 'MainRetail 7';
  Application.HelpFile := 'C:\work\NewRetail - next\SCREEN HELP.HLP';
  Application.CreateForm(TDMGlobal, DMGlobal);
  Application.CreateForm(TDMParent, DMParent);
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TDMServiceOrder, DMServiceOrder);
  Application.CreateForm(TMainMenu, MainMenu);
  Application.CreateForm(TPassword, Password);
  Application.CreateForm(TFrmMsgBox, FrmMsgBox);
  Application.CreateForm(TfrmSendToVendorView, frmSendToVendorView);
  Application.CreateForm(TvwAdjustQtyReasonUpsert, vwAdjustQtyReasonUpsert);
  Application.Run;
end.
