/*
REM The batch file invokes BRCC32 then will immediately
REM Jump to the END branch, bypassing the res file declarations
@ECHO OFF
CLS
"E:\Delphi3\BIN\Brcc32.exe" -foc:\Wintemp\GraphBmp\GraphBmp -32 -v C:\Wintemp\GraphBmp\GraphBmp.bat
GOTO End
*/

/* BITMAPS */
3DRISER1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\3DRiser1.bmp"
3DRISER2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\3DRiser2.bmp"
3DRISER3 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\3DRiser3.bmp"
3DRISER4 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\3DRiser4.bmp"
3DSURFACE1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\3DSurface1.bmp"
3DSURFACE2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\3DSurface2.bmp"
3DSURFACE3 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\3DSurface3.bmp"
AREA1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Area1.bmp"
AREA2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Area2.bmp"
AREA3 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Area3.bmp"
AREA4 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Area4.bmp"
AREA5 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Area5.bmp"
AREA6 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Area6.bmp"
BAR1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Bar1.bmp"
BAR2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Bar2.bmp"
BAR3 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Bar3.bmp"
BAR4 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Bar4.bmp"
BAR5 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Bar5.bmp"
BAR6 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Bar6.bmp"
BUBBLE1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Bubble1.bmp"
BUBBLE2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Bubble2.bmp"
DOUGHNUT1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Doughnut1.bmp"
DOUGHNUT2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Doughnut2.bmp"
DOUGHNUT3 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Doughnut3.bmp"
LINE1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Line1.bmp"
LINE2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Line2.bmp"
LINE3 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Line3.bmp"
LINE4 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Line4.bmp"
LINE5 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Line5.bmp"
LINE6 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Line6.bmp"
PIE1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Pie1.bmp"
PIE2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Pie2.bmp"
PIE3 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Pie3.bmp"
PIE4 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Pie4.bmp"
RADAR1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Radar1.bmp"
RADAR2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Radar2.bmp"
RADAR3 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Radar3.bmp"
STOCK1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Stock1.bmp"
STOCK1CR BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Stock1Cr.bmp"
STOCK2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Stock2.bmp"
STOCK2CR BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Stock2Cr.bmp"
STOCK3 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Stock3.bmp"
STOCK4 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Stock4.bmp"
STOCK5 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Stock5.bmp"
STOCK6 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\Stock6.bmp"
XYSCATTER1 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\XYScatter1.bmp"
XYSCATTER2 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\XYScatter2.bmp"
XYSCATTER3 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\XYScatter3.bmp"
XYSCATTER4 BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\XYScatter4.bmp"
XYSCATTERCR BITMAP LOADONCALL MOVEABLE DISCARDABLE "C:\Wintemp\GraphBmp\XYScatterCr.bmp"

/* ICONS */

/* CURSORS */

/* AVI Files */

/* WAV Files */
/*
:End */
