program SIMain;

uses
  Forms,
  uSisMain in 'uSisMain.pas' {SisMain},
  uSisSenha in 'uSisSenha.pas' {SisSenha},
  uSisUsuarioFch in 'uSisUsuarioFch.pas' {SisUsuarioFch},
  uSisEmpresaList in 'uSisEmpresaList.pas' {SisEmpresaList},
  uFinLancamentoTipoFch in 'uFinLancamentoTipoFch.pas' {FinLancamentoTipoFch},
  uFinContaCorrenteList in 'uFinContaCorrenteList.pas' {FinContaCorrenteList},
  uFinContaCorrenteFch in 'uFinContaCorrenteFch.pas' {FinContaCorrenteFch},
  uFinQuitacaoMeioFch in 'uFinQuitacaoMeioFch.pas' {FinQuitacaoMeioFch},
  uFinLancamentoList in 'uFinLancamentoList.pas' {FinLancamentoList},
  uFinQuitacaoFch in 'uFinQuitacaoFch.pas' {FinQuitacaoFch},
  uFinQuitacaoMoverHelp in 'uFinQuitacaoMoverHelp.pas' {FinQuitacaoMoverHelp},
  uFinLancamentoFch in 'uFinLancamentoFch.pas' {FinLancamentoFch},
  uFinQuitacaoToolBarMover in 'uFinQuitacaoToolBarMover.pas' {FinQuitacaoToolBarMover},
  uFinLancamentoTrackDlg in 'uFinLancamentoTrackDlg.pas' {FinLancamentoTrackDlg},
  uFinCentroCustoFch in 'uFinCentroCustoFch.pas' {FinCentroCustoFch},
  uFinCentroCustoTBrw in 'uFinCentroCustoTBrw.pas' {FinCentroCustoTBrw},
  uSisMoedaFch in 'uSisMoedaFch.pas' {SisMoedaFch},
  uFinBancoFch in 'uFinBancoFch.pas' {FinBancoFch},
  uFinBancoAgenciaFch in 'uFinBancoAgenciaFch.pas' {FinBancoAgenciaFch},
  uFinDocumentoDesdobramentoFch in 'uFinDocumentoDesdobramentoFch.pas' {FinDocumentoDesdobramentoFch},
  uSisGrupoFch in 'uSisGrupoFch.pas' {SisGrupoFch},
  uFinLancamentoProgramacaoDlg in 'uFinLancamentoProgramacaoDlg.pas' {FinLancamentoProgramacaoDlg},
  uFinFluxoCaixa in 'uFinFluxoCaixa.pas' {FinFluxoCaixa},
  uFinDesdobramentoTipoFch in 'uFinDesdobramentoTipoFch.pas' {FinDesdobramentoTipoFch},
  uSisSegurancaFrm in 'uSisSegurancaFrm.pas' {SisSegurancaFrm},
  uSisMoedaCotacaoFch in 'uSisMoedaCotacaoFch.pas' {SisMoedaCotacaoFch},
  uFinQuitacaoList in 'uFinQuitacaoList.pas' {FinQuitacaoList},
  uFinContaCorrenteMovList in 'uFinContaCorrenteMovList.pas' {FinContaCorrenteMovList},
  uFinContaCorrenteAjustaDlg in 'uFinContaCorrenteAjustaDlg.pas' {FinContaCorrenteAjustaDlg},
  uSisFeriadoFch in 'uSisFeriadoFch.pas' {SisFeriadoFch},
  uSisFeriadoList in 'uSisFeriadoList.pas' {SisFeriadoList},
  uSisSelPerfilDlg in 'uSisSelPerfilDlg.pas' {SisSelPerfilDlg},
  uFinLancamentoTipoTree in 'uFinLancamentoTipoTree.pas' {FinLancamentoTipoTree},
  uFinLancamentoQrp in 'uFinLancamentoQrp.pas' {FinLancamentoQrp: TQuickRep},
  uFinDocumentoTipoFch in 'uFinDocumentoTipoFch.pas' {FinDocumentoTipoFch},
  uSisPropertyEditorFrm in 'uSisPropertyEditorFrm.pas' {SisPropertyEditorFrm},
  uSisEmpresaFch in 'uSisEmpresaFch.pas' {SisEmpresaFch},
  uSisSenhaTrocaDlg in 'uSisSenhaTrocaDlg.pas' {SisSenhaTrocaDlg},
  uSisUsuarioList in 'uSisUsuarioList.pas' {SisUsuarioList},
  uFinBancoAgenciaList in 'uFinBancoAgenciaList.pas' {FinBancoAgenciaList},
  uFinBancoList in 'uFinBancoList.pas' {FinBancoList},
  uFinDocumentoTipoList in 'uFinDocumentoTipoList.pas' {FinDocumentoTipoList},
  uFinQuitacaoMeioList in 'uFinQuitacaoMeioList.pas' {FinQuitacaoMeioList},
  uSisMoedaList in 'uSisMoedaList.pas' {SisMoedaList},
  uSisGrupoList in 'uSisGrupoList.pas' {SisGrupoList},
  uSisMenuEditorFch in 'uSisMenuEditorFch.pas' {SisMenuEditorFch},
  uSisMenuFxd in 'uSisMenuFxd.pas' {SisMenuFxd},
  uSisDepartamentoFch in 'uSisDepartamentoFch.pas' {SisDepartamentoFch},
  uSisPessoaList in 'uSisPessoaList.pas' {SisPessoaList},
  uSisPessoaProcuraFrm in 'uSisPessoaProcuraFrm.pas' {SisPessoaProcuraFrm},
  uDM in 'uDM.pas' {DM: TDataModule},
  uFinLancamentoTipoTreeFch in 'uFinLancamentoTipoTreeFch.pas' {FinLancamentoTipoTreeFch},
  uFinCentroCustoTreeFch in 'uFinCentroCustoTreeFch.pas' {FinCentroCustoTreeFch},
  uFinTransferenciaFch in 'uFinTransferenciaFch.pas' {FinTransferenciaFch},
  uFinTransferenciaList in 'uFinTransferenciaList.pas' {FinTransferenciaList},
  uFinHoraFch in 'uFinHoraFch.pas' {FinHoraFch},
  uFinMeioQuitacaoFch in 'uFinMeioQuitacaoFch.pas' {FinMeioQuitacaoFch},
  uFinHoraList in 'uFinHoraList.pas' {FinHoraList},
  uSisPessoaFch in 'uSisPessoaFch.pas' {SisPessoaFch},
  uFinLancamentoTipoList in 'uFinLancamentoTipoList.pas' {FinLancamentoTipoList},
  uFinCentroCustoList in 'uFinCentroCustoList.pas' {FinCentroCustoList},
  uFinBankAccountsListInfo in 'uFinBankAccountsListInfo.pas' {FinBankAccountsListInfo},
  uSisReports in 'uSisReports.pas' {SisReports},
  uSisQuickRepFch in 'uSisQuickRepFch.pas' {SisQuickRepFch},
  uFrameFilterAcc in 'uFrameFilterAcc.pas' {FrameFilterAcc: TFrame},
  uSisTextEditorFrm in 'uSisTextEditorFrm.pas' {sisTextEditorFrm},
  uSisWizardFrm in 'uSisWizardFrm.pas' {SisWizardFrm},
  uFinChoicerFrm in 'uFinChoicerFrm.pas' {FinChoicerFrm},
  uFinLancamentoDesdobramentoFch in 'uFinLancamentoDesdobramentoFch.pas' {FinLancamentoDesdobramentoFch},
  uFinLancamentoCalc in 'uFinLancamentoCalc.pas',
  uQuicken in '..\Repository\uQuicken.pas',
  uSaveToFile in '..\Repository\uSaveToFile.pas',
  uSqlFunctions in '..\Repository\uSqlFunctions.pas',
  uNumericFunctions in '..\Repository\uNumericFunctions.pas',
  uDataBaseFunctions in '..\Repository\uDataBaseFunctions.pas',
  uLanguageFunctions in '..\Repository\uLanguageFunctions.pas',
  ufrmServerInfo in '..\Repository\ufrmServerInfo.pas' {FrmServerInfo},
  uDateTimeFunctions in '..\Repository\uDateTimeFunctions.pas',
  uSystemTypes in '..\Repository\uSystemTypes.pas',
  uStringFunctions in '..\Repository\uStringFunctions.pas',
  uClasseFunctions in '..\Repository\uClasseFunctions.pas',
  uCharFunctions in '..\Repository\uCharFunctions.pas',
  uVarianteFunctions in '..\Repository\uVarianteFunctions.pas',
  uParamFunctions in '..\Repository\uParamFunctions.pas',
  uSystemConst in '..\Repository\uSystemConst.pas',
  uComboFiltroFunctions in '..\Repository\uComboFiltroFunctions.pas',
  uParentAllFrm in 'FrmParents\uParentAllFrm.pas' {ParentAllFrm},
  uParentFixedFrm in 'FrmParents\uParentFixedFrm.pas' {ParentFixedFrm},
  uParentDM in 'FrmParents\uParentDM.pas' {ParentDM: TDataModule},
  uParentDialogFrm in 'FrmParents\uParentDialogFrm.pas' {ParentDialogFrm},
  uParentFch in 'FrmParents\uParentFch.pas' {ParentFch},
  uParentFchList in 'FrmParents\uParentFchList.pas' {ParentFchList},
  uParentFchTab in 'FrmParents\uParentFchTab.pas' {ParentFchTab},
  uParentTree in 'FrmParents\uParentTree.pas' {ParentTree},
  uParentTreeBrw in 'FrmParents\uParentTreeBrw.pas' {ParentTreeBrw},
  uParentTreeFch in 'FrmParents\uParentTreeFch.pas' {ParentTreeFch},
  uParentTreeView in 'FrmParents\uParentTreeView.pas' {ParentTreeView},
  uParentReport in 'FrmParents\uParentReport.pas' {ParentReport: TQuickRep},
  uParentReportFrm in 'FrmParents\uParentReportFrm.pas' {ParentReportFrm},
  uParentBrwFilterHelp in 'FrmParents\uParentBrwFilterHelp.pas' {ParentBrwFilterHelp},
  uParentBrwWaitFrm in 'FrmParents\uParentBrwWaitFrm.pas' {ParentBrwWaitFrm},
  uParentList in 'FrmParents\uParentList.pas' {ParentList},
  uParentModal in 'FrmParents\uParentModal.pas' {ParentModalFrm},
  uParentListInfo in 'FrmParents\uParentListInfo.pas' {ParentListInfo},
  uMsgBox in '..\Repository\uMsgBox.pas' {FrmMsgBox},
  uParentListFilterHelp in 'FrmParents\uParentListFilterHelp.pas' {ParentListFilterHelp},
  uParentListWaitFrm in 'FrmParents\uParentListWaitFrm.pas' {ParentListWaitFrm},
  uFinContaCorrenteReconcile in 'uFinContaCorrenteReconcile.pas' {FinContaCorrenteReconcile},
  uQuickBooks in '..\Repository\uQuickBooks.pas',
  uWelcome in 'uWelcome.pas' {FrmWelcome},
  uPeachTree in '..\Repository\uPeachTree.pas',
  uParentWizard in 'FrmParents\uParentWizard.pas' {ParentWizard},
  uSisEntityWiz in 'uSisEntityWiz.pas' {SisEntityWiz},
  uRegistry in '..\Repository\uRegistry.pas',
  uDMGlobal in '..\Repository\uDMGlobal.pas' {DMGlobal: TDataModule},
  uXML in '..\Repository\uXML.pas',
  uMsgConstant in '..\Repository\uMsgConstant.pas' {FrmMsgConstant},
  ufrmLanguage in '..\Repository\ufrmLanguage.pas' {frmLanguage},
  uModuleConfig in 'uModuleConfig.pas',
  uFinTaxComper in 'uFinTaxComper.pas' {FinTaxComper},
  uOMTranslateScript in '..\Repository\uOMTranslateScript.pas',
  uFinLancamentoTipoResult in 'uFinLancamentoTipoResult.pas' {FinLancamentoTipoResult},
  uFinLancamentoTipoListTree in 'uFinLancamentoTipoListTree.pas' {FinLancamentoTipoListTree},
  uFinEmprestimoFrm in 'uFinEmprestimoFrm.pas' {FinEmprestimoFrm},
  uSisMunicipio in 'uSisMunicipio.pas' {SisMunicipio},
  uFrmPrintBoleto in 'uFrmPrintBoleto.pas' {FrmPrintBoleto},
  uFrmExportBoleto in 'uFrmExportBoleto.pas' {FrmExportBoleto};

{$R *.RES}
{$R AppRes.RES}

begin

  Application.Initialize;
  Application.Title := 'Office Manager';
  Application.CreateForm(TDMGlobal, DMGlobal);
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TSisMain, SisMain);
  Application.CreateForm(TSisSenha, SisSenha);
  Application.CreateForm(TFrmMsgBox, FrmMsgBox);
  Application.Run;

end.
