USE [a0000748__2014-03-30]
GO
/****** Object:  Table [dbo].[SysFunction]    Script Date: 04/16/2014 10:08:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SysFunction](
	[IDSysFunction] [int] NOT NULL,
	[IDMenu] [int] NOT NULL,
	[IDSubMenu] [int] NOT NULL,
	[SysFunction] [varchar](100) NOT NULL,
	[ReplLastChange] [datetime] NULL,
 CONSTRAINT [PK__SysFunction__3BFFE745] PRIMARY KEY CLUSTERED 
(
	[IDSysFunction] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[SysFunction]  WITH NOCHECK ADD  CONSTRAINT [FK_MenuItem_SysFunction_IDMenuIDSubMenu] FOREIGN KEY([IDMenu], [IDSubMenu])
REFERENCES [dbo].[MenuItem] ([IDMenu], [IDSubMenu])
NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[SysFunction] CHECK CONSTRAINT [FK_MenuItem_SysFunction_IDMenuIDSubMenu]
GO
