USE [a0000748__2014-03-30]
GO
/****** Object:  Table [dbo].[InvSize]    Script Date: 04/16/2014 10:08:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[InvSize](
	[IDSize] [int] NOT NULL,
	[SizeName] [varchar](20) NOT NULL,
	[Hidden] [bit] NULL,
	[Desativado] [bit] NULL,
	[System] [bit] NULL,
	[CodSize] [varchar](10) NULL,
	[ReplLastChange] [datetime] NULL,
 CONSTRAINT [PK__InvSize__1367E606] PRIMARY KEY CLUSTERED 
(
	[IDSize] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[InvSize] ADD  CONSTRAINT [DF_Zero]  DEFAULT (0) FOR [Hidden]
GO
ALTER TABLE [dbo].[InvSize] ADD  CONSTRAINT [DF_Zero2]  DEFAULT (0) FOR [Desativado]
GO
ALTER TABLE [dbo].[InvSize] ADD  CONSTRAINT [DF_Zero3]  DEFAULT (0) FOR [System]
GO
