USE [a0000748__2014-03-30]
GO
/****** Object:  Table [dbo].[PT_GlobalMapping]    Script Date: 04/16/2014 10:08:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PT_GlobalMapping](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDStore] [int] NOT NULL,
	[StoreCode] [varchar](255) NULL,
 CONSTRAINT [PK_PT_GlobalMapping] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
