USE [a0000748__2014-03-30]
GO
/****** Object:  Table [dbo].[Mnt_Controler]    Script Date: 04/16/2014 10:08:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Mnt_Controler](
	[Software] [varchar](50) NOT NULL,
	[Info] [text] NULL,
	[ReplLastChange] [datetime] NULL,
 CONSTRAINT [XPKMnt_Controler] PRIMARY KEY CLUSTERED 
(
	[Software] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
