USE [a0000748__2014-03-30]
GO
/****** Object:  Table [dbo].[Rep_Folder]    Script Date: 04/16/2014 10:08:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Rep_Folder](
	[FolderId] [int] NOT NULL,
	[Name] [varchar](60) NULL,
	[ParentId] [int] NULL,
	[ReplLastChange] [datetime] NULL,
 CONSTRAINT [XPKRep_Folder] PRIMARY KEY CLUSTERED 
(
	[FolderId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
