USE [a0000748__2014-03-30]
GO
/****** Object:  Table [dbo].[TagModel]    Script Date: 04/16/2014 10:08:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TagModel](
	[PKTagModel] [int] IDENTITY(1,1) NOT NULL,
	[IDTag] [int] NOT NULL,
	[IDModel] [int] NOT NULL,
 CONSTRAINT [PK_TagModel] PRIMARY KEY CLUSTERED 
(
	[PKTagModel] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TagModel]  WITH CHECK ADD  CONSTRAINT [FK_TagModel] FOREIGN KEY([IDModel])
REFERENCES [dbo].[Model] ([IDModel])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TagModel] CHECK CONSTRAINT [FK_TagModel]
GO
