unit uMainRetailKeyConst;

interface

const
  //SOFTWARE LIST
  SOFTWARE_IE = 'Import/Export';
  SOFTWARE_MR = 'MainRetail';
  SOFTWARE_OM = 'OfficeManager';
  SOFTWARE_PC = 'PetCenter';
  SOFTWARE_RP = 'Report';

  //STORE INI FILE
  LICENSE_FILE_COMPANY_HEADER = 'Company';
  LICENSE_FILE_COMPANY_KEY    = 'Key';

  LICENSE_FILE_SOFTWARE_COMPUTER  = 'Computer';
  LICENSE_FILE_SOFTWARE_USER      = 'Users';
  LICENSE_FILE_SOFTWARE_MODULE1   = 'Module1';
  LICENSE_FILE_SOFTWARE_MODULE2   = 'Module2';
  LICENSE_FILE_SOFTWARE_MODULE3   = 'Module3';
  LICENSE_FILE_SOFTWARE_MODULE4   = 'Module4';
  LICENSE_FILE_SOFTWARE_MODULE5   = 'Module5';
  LICENSE_FILE_SOFTWARE_EXPIRES   = 'Expires';

  //IMPORT/EXPORT MODULES
  SOFTWARE_IE_EXP_PO        = 'EXP_PO';
  SOFTWARE_IE_EXP_PEACHTREE = 'EXP_PEACHTREE';
  SOFTWARE_IE_EXP_QB        = 'EXP_QB_';
  SOFTWARE_IE_IMP_PO        = 'IMP_PO';
  SOFTWARE_IE_IMP_INV       = 'IMP_INV';
  SOFTWARE_IE_IMP_ENTITY    = 'IMP_ENTITY';
  SOFTWARE_IE_IMP_PET       = 'IMP_PET';
  SOFTWARE_IE_CAT_PRICE_COM = 'CAT_PRICE_COM';
  SOFTWARE_IE_CAT_INV_UPD   = 'CAT_INV_UPD';
  SOFTWARE_IE_CAT_SRCH      = 'CAT_SRCH';
  SOFTWARE_IE_CAT_SYNC      = 'CAT_SYNC';
  { Alex 29/03/2011 }
  SOFTWARE_IE_IMP_VC        = 'IMP_VEND_CAT';

implementation

end.
