unit uSystemConst;

interface

uses Messages;

const
  //SOFTVAR CONST                                                     
  PDV_MD5 = '00fe96bc61c96a87414ab6874098b584';

  //Main Retail Const
  STORE_MARK           = '#STORE_ACCESS_LIST#';

  TEMP_TABLE           = '*TempTable*';

  REGISTRY_PATH        = 'SOFTWARE\Applenet\MainRetail';

  REPORT_FILE          = 'MainReport.exe';
  MRREPORT_FILE        = 'MRReport.exe';

  MR_BRW_REG_PATH      = '\SOFTWARE\RetailSystems\MainRetail\CurrentViews\';
  MR_IMP_EXP_REG_PATH  = '\SOFTWARE\RetailSystems\ImportExport\CurrentViews\';
  PET_BRW_REG_PATH      = '\SOFTWARE\RetailSystems\MRPet\CurrentViews\';

  PAPER_TYPE_4A        = 0;
  PAPER_TYPE_80COL     = 1;

  EMPRESA_DEFAULT      = 0;

  MEDIA_TYPE_TOURGROUP = 1;
  MEDIA_TYPE_GUIDE     = 2;

  XPRESS_SALE_RETAIL      = 0;
  XPRESS_SALE_SUPERMARKET = 1;
  XPRESS_SALE_RETAIL2     = 2;

  TAX_MODE_MANAGER     = 1;
  TAX_MODE_SALEPERSON  = 2;
  TAX_MODE_AUTO        = 3;

  //Inventory Count
  INV_COUNT_CYCLE    = 1;
  INV_COUNT_PHYSICAL = 2;
  INV_COUNT_LIVE     = 3;
  INV_COUNT_STARTUP  = 4;

  //Payments
  FORM_OF_PAYMENT_NOW   = 0;
  FORM_OF_PAYMENT_LATER = 1;

  PARAM_START_LAYAWAY       = 'start_layaway';
  PARAM_START_INVENT_ADJST  = 'start_inv_adjst';

  TYPE_VENDORID = 1;
  TYPE_GUIDEID  = 2;
  TYPE_AGENCYID = 3;

  REQ_TYPE_SALESPERSON = 'P';
  REQ_TYPE_COMPUTER    = 'C';
  REQ_TYPE_BUYER       = 'B';

  REQ_STATUS_ONREQUEST   = 'R';
  REQ_STATUS_ONORDER     = 'O';
  REQ_STATUS_ONARRIVED   = 'A';

  SQL_STATUS_NO_CONNECTED = 'Not connected';
  SQL_STATUS_CONNECTED    = 'Connected';
  SQL_STATUS_ERROR        = 'Connection error';

  HIST_RETAIL = 1;
  HIST_COST   = 2;
  HIST_MARKUP = 3;
  HIST_GROSS  = 4;
  HIST_PROFIT = 5;


  DRAW_KICK_TYPE_SALE       = 1;
  DRAW_KICK_TYPO_CLOSE_REG  = 2;
  DRAW_KICK_TYPO_WIDRAW     = 3;
  DRAW_KICK_TYPO_PETTY_CASH = 4;
  DRAW_KICK_TYPO_NO_SALE    = 5;
  DRAW_KICK_TYPO_OPEN_CASH  = 6;


  PESSOA_TIPO_CLIENTE      = 1;
  PESSOA_TIPO_FORNECEDOR   = 2;
  PESSOA_TIPO_COMISSIONADO = 3;
  PESSOA_TIPO_VENDEDOR     = 4;
  PESSOA_TIPO_GUIA         = 5;
  PESSOA_TIPO_AGENCIA      = 6;
  PESSOA_TIPO_FABRICANTE   = 7;

  SALE_PRESALE           = 0;
  SALE_CASHREG           = 1;
  SALE_INVOICE           = 2;
  SALE_UNLOCK_PRESALE    = 3;
  SALE_SPLIT_PRESALE     = 4;
  SALE_MOVE_PRESALE      = 5;
  SALE_CANCELED          = 6;

  USER_TYPE_ADMINISTRATOR  = 1;
  USER_TYPE_MANAGER        = 2;
  USER_TYPE_ASSIST_MANAGER = 6; // ** Ivanil
  USER_TYPE_CASHIER        = 3; // ** Ivanil
  USER_TYPE_CASHIER_PO     = 5; // ** Ivanil

  REC_INVOICE              = 1;
  REC_SLIP                 = 2;

  PAY_TYPE_CASH          = 1;
  PAY_TYPE_VISA          = 2;
  PAY_TYPE_AMERICAN      = 3;
  PAY_TYPE_MASTER        = 4;
  PAY_TYPE_CHECK         = 5;

  // from tipo ( field ) in table MeioPag related to type of payment screen ( label type )
  PAYMENT_TYPE_CASH         = 1;
  PAYMENT_TYPE_CARD         = 2;
  PAYMENT_TYPE_OTHER        = 3;
  PAYMENT_TYPE_CHECK        = 4;
  PAYMENT_TYPE_CREDIT       = 5;
  PAYMENT_TYPE_GIFTCARD     = 6;
  PAYMENT_TYPE_DEBIT        = 7;
  PAYMENT_TYPE_BONUSBUCK    = 8;
  PAYMENT_TYPE_STOREACCOUNT = 9;
  //amfsouza 10.18.2011 - Others gift cards to be processed.
  PAYMENT_TYPE_GIFTCARD_OTHERS = 10;

  PAYMENT_PLACE_LOJA          = 0;
  PAYMENT_PLACE_CONTRAENTREGA = 1;
  PAYMENT_PLACE_OUTROS        = 2;
  PAYMENT_PLACE_EMPTY         = 3;

  DELIVER_TYPE_ONHAND    = 1;

  LANC_TYPE_SALE         = 1;
  LANC_TYPE_BUY          = 2;

  ST_CASHREG_OPEN        = 1;
  ST_CASHREG_CLOSE       = 2;
  ST_CASHREG_CONF        = 3;

  TIPODOC_SALE           = 1;
  TIPODOC_BUY            = 2;
  TIPODOC_TRANSF         = 3;
  TIPODOC_PEDSALE        = 4;

  MOV_TYPE_SALE          = 1;
  MOV_TYPE_BUY           = 2;
  MOV_TYPE_ADJUST        = 3;

  PARAM_TAX              = 1;
  PARAM_SALEONNEGATIVE   = 2;
  PARAM_FASTSALE         = 3;
  PARAM_REFRESHONINSERT  = 4;
  PARAM_REFRESHINTERVAL  = 5;
  PARAM_REFRESHBROWSE    = 6;
  PARAM_MAXROWS          = 7;
  PARAM_MODIFYCOST       = 8;
  PARAM_CASHREGRESTANT   = 9;
  PARAM_LICENSE          = 10;
  PARAM_MAXCASHALLOWED   = 11;
  PARAM_CLOSECASHRANDOM  = 12;
  PARAM_MAXQTYCOMPUTERREQ = 13;
  PARAM_MINSALECOMPUTERREQ = 14;
  PARAM_INCLUDEPREPURCHASE = 15;
  PARAM_ANYONEMANAGECASHREG = 31;
  PARAM_SHOWTABNOCUSTUMERREGISTER = 32;
  PARAM_SHOWTABCUSTUMERREGISTER = 33;
  PARAM_SHOWTABTOURGROUP = 34;
  PARAM_COMMISSIONBONUS = 35;
  PARAM_SHOWNAME_NOREGISTERCUSTUMER = 36;
  PARAM_MAX_WORKING_HOUR_PER_DAY = 37;
  PARAM_SHOW_PRICE_PRE_RECEIVE  = 38;
  PARAM_SHOW_MENU_ICONS = 39;
  PARAM_SHOW_LAYAWAY_CR_HIST = 41;
  PARAM_SHOW_LAYAWAY_INVOICE_HIST = 40;
  PARAM_PRINT_DEPOSIT = 42;
  PARAM_SHOWTABLAYAWAY = 43;
  PARAM_CHECKSERIALNUMBER = 44;
  PARAM_MARKUPOVERCOST = 45;
  PARAM_PRINT_ON_OPENCASHREG = 46;
  PARAM_NUM_ITEM_TO_PRINT = 47;
  PARAM_DISPLAY_PRE_DATADO = 48;
  PARAM_CONFIRM_DELIVERY_ON_SALE = 49;
  PARAM_DISPLAY_PAYMENT_PLACE = 50;
  PARAM_ENTER_LAYAWAY_FULL_AMOUNT = 51;
  PARAM_INVOICE_SHOW_TAB_OTHER_COSTS = 52;
  PARAM_INVOICE_SHOW_TAB_PAYMENTS = 53;
  PARAM_INVOICE_SHOW_TAB_AGENTS = 54;
  PARAM_INVOICE_SHOW_TAB_DELIVERY = 55;
  PARAM_INVOICE_SHOW_TAB_DEPOSIT_DATE = 56;
  PARAM_INVOICE_SHOW_TAB_DISCOUNT = 57;
  PARAM_MAX_NUMBER_PAYMENTS = 58;
  PARAM_CONSULTA_SERASA = 59;
  PARAM_CONSULTA_ZIPCODE = 60;
  PARAM_MAX_NUMBER_DAYS_PAYING_NOW = 61;
  PARAM_CONFIRM_DELIVERY_AFTER_FINISH_SALE = 62;
  PARAM_SALE_SCREEN_TYPE = 63;
  PARAM_TAX_EXEMPT_ON_SALE = 64;
  PARAM_DISPLAY_QTY_FLOATING = 65;
  PARAM_TAX_IN_COSTPRICE = 66;
  PARAM_PETSHOP_OPTIONS = 67;
  PARAM_USE_ESTIMATED_COST = 68;
  PARAM_MARK_DELIVERY_HOUR = 69;
  PARAM_DISPLAY_CUSTOMER_INFO = 70;
  PARAM_VERIFY_PGTO_BEFORE_DELIVERY = 71;
  PARAM_TAX_COST_USE_MARKUP_ON_COST = 72;
  PARAM_PUPPY_TRACKER_INTEGRATION = 73;
  PARAM_ASK_PASSWORD_BEFORE_OPEN_SOFTWARE = 74;
  PARAM_CALC_MARGIN = 75;
  PARAM_CALC_ROUNDING = 76;
  PARAM_REMOVE_BARCODE_DIGIT = 77;
  PARAM_SEARCH_MODEL_AFTER_BARCODE = 78;
  PARAM_AUTO_GENERATE_MODEL = 79;
  PARAM_APPLY_PROMO_ON_SALE = 80;
  PARAM_PROMPT_COMMISSIONER_ON_SALE = 81;
  PARAM_SALECODE_ON_CREATE_SALE = 82;
  PARAM_TREAT_HOLD_AS_INVOICE = 83;
  PARAM_SEND_ITEM_FOR_TRASH = 84;
  PARAM_USE_FRACTIONARY_QTY = 85;
  PARAM_GIFT_EXP_DATE       = 86;
  PARAM_PROGRESSIVE_QTY_DISCOUNT = 87;
  PARAM_USE_CATALOG = 88;
  PARAM_ASK_SALEPRICE = 89;
  PARAM_MIN_BARCODE_LENGTH = 90;
  PARAM_PETCENTER_INTEGRATION = 91;
  PARAM_APPLY_BONUS_ON_SALE = 92;
  PARAM_CREATE_SUBCATEGORY_ON_IMPORT = 93;
  PARAM_LIMIT_LAYAWAY_ON_MONTH = 94;
  PARAM_VALIDATE_CASE_QTY_ON_HOLD = 95;
  PARAM_APPLY_INV_DISCOUNT_ON_ITEMS = 96;
  PARAM_USE_PRICE = 97;
  PARAM_USE_IDENT_NUMBER_SERIAL = 98;
  PARAM_CALC_COMMISSION_ON_INVOICE = 99;
  PARAM_AUTO_GENERATE_TRANSF = 100;
  PARAM_CALC_COMM_ON_PAID_HOLD = 101;
  PARAM_SAVE_UNPOSTED_PAYMENT_ON_CLOSE = 102;
  PARAM_DISABLE_INCREASE_PRICE = 103;
  PARAM_INVOICE_SHOW_TAB_COMPLEMENT = 104;  
  PARAM_UPDATE_BUDGET_PRICE = 105;  
  PARAM_CONFIRM_BUDGET = 106;  
  PARAM_AUTO_GENERATE_PUR_DOC = 107;
  PARAM_DISABLE_FREIGHT_OTHERCOST = 108;
  PARAM_REMOVE_REMINDED_PO = 109;
  PARAM_SO_TYPE = 110;
  PARAM_DISABLE_SO_DEFECTS = 111;
  PARAM_USE_LOT_CONTROL = 112;
  PARAM_INV_RETURN_WITH_STORECREDIT_ONLY = 113;
  PARAM_PURCHASE_HIST_BACK_MONTH = 114;
  PARAM_SALE_REPEAT_CUSTOMER_SALESPERSON = 115;
  PARAM_ENABLE_INDUSTRY_OPTION = 116;
  //amfsouza 06.03.2011
  PARAM_INCREASE_SELLINGPRICE_ONLY = 117;

  //Antonio 03/20/2017
  PARAM_RECALCULATE_DISCOUNT_EACH_ITEM = 118;
  PARAM_ASK_MEDIA_FILES = 119;

  PO_ONTIME              = 0;
  PO_ONTIME_ARRIVED      = 1;
  PO_ONDELAY             = 2;
  PO_ONDELAY_ARRIVED     = 3;
  PO_ALL                 = 4;
  PO_ALL_ARRIVED         = 5;

  CASHREG_OPEN           = 0;
  CASHREG_CLOSE          = 1;
  CASHREG_ERROR          = 2;
  TRIAL_LIMIT            = 6000;

  CASHREG_TYPE_POS       = 1;
  CASHREG_TYPE_OFFICE    = 2;
  CASHREG_TYPE_FULL_POS  = 3;
  CASHREG_TYPE_SHIPPING  = 4;

  TAX_OP_TYPE_SALE     = 1;
  TAX_OP_TYPE_PURCHASE = 2;

  SALE_TAX_TYPE_CHARGE  = 1;
  SALE_TAX_TYPE_GOV     = 2;

  PURCHASE_PRE          = 1;
  PURCHASE_FINAL        = 2;
  PURCHASE_HISTORY      = 3;

  //Update Pack 3
  SQL_REG_PATH = 'Software\Microsoft\MSSQLServer\MSSQLServer\CurrentVersion';
  SQL_GO       = 'GO';

  //Main Retail ID fields
  MR_INVENTORY_MOV_ID       = 'InventoryMov.IDInventoryMov';
  MR_GROUP_COST_ID          = 'GroupCost.IDCost';
  MR_TIME_CONTROL_ID        = 'TMC_TimeControl.IDTime';
  MR_MODEL_ID               = 'Model.IDModel';
  MR_PESSOA_ID              = 'Pessoa.IDPessoa';
  MR_SYSTEMUSER_ID          = 'SystemUser.IDUser';
  MR_STORE_ID               = 'Store.IDStore';
  MR_TAX_CATEG_ID           = 'TaxCategory.IDTaxCategory';
  MR_CASH_REG_ID            = 'CashRegister.IDCashRegister';
  MR_CATEGORY_ID            = 'TabGroup.IDGroup';
  MR_REQUEST_ID             = 'Request.IDRequest';
  MR_PRESALE_ID             = 'Invoice.IDPreSale';
  MR_APPHISTORY_ID          = 'Sis_AppHistory.IDHistory';
  MR_PURCHASE_ITEM_ID       = 'Pur_PurchaseItem.IDPurchaseItem';
  MR_PURCHASE_ITEM_SN_ID    = 'Pur_PurchaseItemSerial.IDPurchaseItemSerial';
  MR_REP_FOLDER_ID          = 'Rep_Folder.FolderId';
  MR_REP_ITEM_ID            = 'Rep_Item.ItemId';
  MR_INV_FEATURE_ID         = 'InvFeatures.IDInvFeatures';
  MR_INV_TECH_FEATURE_ID    = 'InvTechFeatures.IDInvTechFeatures';
  MR_INV_CUSTOMER_CREDIT_ID = 'CustomerCredit.IDCustomerCredit';
  MR_INV_ESTIMATED_ID       = 'Estimated.IDEstimated';
  MR_INV_ESTIMATED_ITEM_ID  = 'EstimatedItem.IDEstimatedItem';
  MR_PURCHASE_VENDOR_TAX_ID = 'VendorTax.IDVendorTax';
  MR_INVOICE_OBS_ID         = 'InvoiceOBS.IDInvoiceOBS';
  MR_VENDOR_MODEL_CODE      = 'VendorModelCode.IDVendorModelCode';
  MR_STORE_VENDOR_ACCOUNT   = 'Mnt_StoreVendorAccount.IDStoreVendorAccount';
  MR_DEFECT_TYPE_ID         = 'DefectType.IDDefectType';
  MR_MODEL_RECEIPT_ID       = 'Inv_ModelReceipt.IDModelReceipt';
  MR_MODEL_TRANSFER_DET_ID  = 'ModelTransfDet.IDModelTransfDet';
  MR_MODEL_TRANSF_SERIAL_ID = 'ModelTransfSerial.IDModelTransfSerial';

  APPLENET_REGISTRY_KEY = 'SOFTWARE\AppleNet';

  //Replication Server
  SYSTEM_STANDALONE_TYPE  = 'STAND_ALONE';
  SYSTEM_SERVER_TYPE      = 'SERVER';
  SYSTEM_CLIENT_TYPE      = 'CLIENT';

  //Detail
  TICKET_MODEL            = '[MODEL]';
  TICKET_DESCRIPTION      = '[DESCRIPTION]';
  TICKET_SP               = '[SP]';
  TICKET_SPN              = '[SP_#]';
  TICKET_BARCODE          = '[BARCODE]';
  TICKET_SERIALNUMBER     = '[SN]';
  TICKET_QTY              = '[QTY]';
  TICKET_UNIT_PRICE       = '[UNITPRICE]';
  TICKET_UNIT_TOTAL       = '[UNIT_TOTAL]';
  TICKET_UNIT             = '[UNIT]';
  TICKET_MANUFACTURER     = '[MANUFACTURER]';
  TICKET_ALIGN_RIGHT      = '{>  <}';
  TICKET_CATEG_TEXT       = '[CATNOTE]';
  //Header
  TICKET_DATE             = '[DATE]';
  TICKET_TIME             = '[TIME]';
  TICKET_CUSTOMER         = '[CUSTOMER]';
  TICKET_MEDIA            = '[MEDIA]';
  TICKET_CASHIER          = '[CASHIER]';
  TICKET_HOLD             = '[HOLD]';
  TICKET_INVOICE          = '[INVOICE]';
  //Totals
  TICKET_NO_TAXABLE       = '[NOTAXABLE]';
  TICKET_TAXABLE          = '[TAXABLE]';
  TICKET_TAX              = '[TAX]';
  TICKET_SUBTOTAL         = '[SUBTOTAL]';
  TICKET_TOTAL            = '[TOTAL]';
  TICKET_CASH_RECEIVED    = '[CASH]';
  TICKET_CHANGE           = '[CHANGE]';
  TICKET_ITEM_DISCOUNT    = '[ITEMDISCOUNT]';
  TICKET_DISCOUNT         = '[DISCOUNT]';
  TICKET_REFUND           = '[REFUND]';
  TICKET_PAYDATE_TYPE     = '[DATE/TYPE/$]';
  //Layaway
  TICKET_PAYMENT_TOTAL    = '[PAYMENT_TOTALS]';
  TICKET_PAYMENT_BALANCE  = '[PAYMENT_BALANCE]';


  COD_GERAL= '_COD_GERAL';

  WM_Start = WM_USER+100;

  INC_VALUE = '*';

  DAY_ADJUST = 1 -(1/86400);

  ORDER_AUTO = -1;
  ORDER_ASC  = 0;
  ORDER_DESC = 1;

  QuitacaoMeioTipo_Especie  = 1;
  QuitacaoMeioTipo_Cartao   = 2;
  QuitacaoMeioTipo_Outros   = 3;
  QuitacaoMeioTipo_Cheque   = 4;

  SIS_IDMOEDA_PADRAO        = 4;
  SIS_IDMOEDACOTACAO_PADRAO = 6;

  ffValor     = '#,##0.00;-#,##.00;0.00';
  ffQtde      = '#,##0.00;-#,##.00;0.00';
  ffDataHora  = 'ddddd hh:mm';
  ffHora      = '#,##0.0;-#,##.0;0.0';
  ffPerc      = '#,##0.00 %';
  fdSQLDate   = 'yyyymmdd';


  MaxModulos = 200;

  //Main menu navigator
  WEB_PRIOR  = 0;
  WEB_NEXT   = 1;

  // Constantes do MainRetail Copatibilidade
  SUGG_CLASS = 'CLASS';
  SUGG_NAME  = 'NAME';
  SUGG_VALUE = 'VALUE';

  QUICK_REP_TOTALSALES = 1;
  QUICK_REP_ITEMSHOLD  = 2;
  QUICK_REP_ITEMSPO    = 3;

  // Model Types
  MODEL_TYPE_MASTER   = 'M';
  MODEL_TYPE_SUB      = 'S';
  MODEL_TYPE_REGULAR  = 'R';
  MODEL_TYPE_SERVICE  = 'V';
  MODEL_TYPE_CREDIT   = 'C';
  MODEL_TYPE_PACKAGE  = 'K';
  MODEL_TYPE_GIFTCARD = 'G';

  //Purchase Fomrula
  PUR_COST     = 'c';
  PUR_FREIGHT  = 'f';
  PUR_OTHER    = 'o';
  PUR_PERCENT  = 'p';
  PUR_MVA      = 'm';
  PUR_DISCOUNT = 'd';

  PUR_TYPE_INVOICE      = 'Invoice';
  PUR_TYPE_PACKING_SLIP = 'Packing Slip';
  PUR_TYPE_COD          = 'C.O.D';

  //InvMovType
  INV_MOVTYPE_SALE             = 1;
  INV_MOVTYPE_BOUGHT           = 2;
  INV_MOVTYPE_DECREASEONHAND   = 3;
  INV_MOVTYPE_INCREASEONHAND   = 4;
  INV_MOVTYPE_RESETUPTOZERO    = 11;
  INV_MOVTYPE_RESETDOWNTOZERO  = 12;
  INV_MOVTYPE_PHYSICALINCREASE = 21;
  INV_MOVTYPE_PHYSICALDECREASE = 22;

  //PromoType
  PROMO_TYPE_SALE          = 1;
  PROMO_TYPE_FREQUENTBUYER = 2;
  PROMO_TYPE_COUPON        = 3;
  PROMO_TYPE_LOYALTY       = 4;

  // Antonio 2014 Jul 24
  // New Promo Types
  NEW_PROMO_TYPE_COUPON = 0;
  NEW_PROMO_TYPE_PROMO = 1;

  { some types are disabled until all type of promo be implemented by new sps.}
  // Antonio 2014 Jul 24
  // Amount Types
  NEW_PROMO_SALE_PRICE = 0;
  NEW_PROMO_QUANTITY = 9; // disabled ( was 1 )
  NEW_PROMO_AMOUNT_OFITEM = 1;  // replaced ( was 2 )
  NEW_PROMO_AMOUNT_OFSUBTOTAL = 8; // disabled ( was 3 )
  NEW_PROMO_PERCENT_OFITEM = 2; // replaced ( was 4 )
  NEW_PROMO_PERCENT_OFSUBTOTAL = 7; // disabled ( was 5 )

  //DiscountType
  DISCOUNT_PROMO_TYPE_PERCENTUAL = 1;
  DISCOUNT_PROMO_TYPE_VALUE      = 2;
  DISCOUNT_PROMO_TYPE_QTY        = 3;
  DISCOUNT_PROMO_TYPE_SALE       = 4;

  //InvoiceOBS Type
  INVOICE_OBS_TYPE_PAYMENT     = 1;
  INVOICE_OBS_TYPE_CUSTOMER    = 2;
  INVOICE_OBS_TYPE_SALESPERSON = 3;

  //PO
  PO_FILE_DIR = 'POFiles\';

  //Credit CardProcessor
  //PROCESSOR_PCCHARGE  = 1;
  NO_PROCESSOR = 0;
  PROCESSOR_MERCURY   = 1;
  PROCESSOR_WORLDPAY  = 2; 
  //PROCESSOR_EMV       = 4;

  // Processing Type
  PROCESSING_TYPE_MANUAL_CHARGE = 0;
  PROCESSING_TYPE_DSICLIENTX = 1;
  PROCESSING_TYPE_DSIPDCX = 2;
  PROCESSING_TYPE_DSIEMVUS = 3;

  IMPORT_TYPE_PO           = 1;
  IMPORT_TYPE_PET          = 2;
  IMPORT_TYPE_COSTUMER     = 3;
  IMPORT_TYPE_VENDOR       = 4;
  IMPORT_TYPE_COMMISSIONED = 5;
  IMPORT_TYPE_SALESMAN     = 6;
  IMPORT_TYPE_GUIDES       = 7;
  IMPORT_TYPE_AGENCY       = 8;
  IMPORT_TYPE_MANUFACTORER = 9;
  IMPORT_TYPE_ANOTHER      = 10;
  IMPORT_TYPE_PROSPECTS    = 11;
  IMPORT_TYPE_INVENTORY    = 12;
  { Alex 03/04/2011 }
  IMPORT_TYPE_VC           = 13;

  EXPORT_TYPE_PO        = 1;
  EXPORT_TYPE_QBOOKS    = 2;
  EXPORT_TYPE_PEACHTREE = 3;

  //TAX TYPE
  TAX_NENHUMA       = 0;
  TAX_TRIBUTAVEL    = 1;
  TAX_NAOTRIBUTAVEL = 2;
  TAX_SUBSTITUICAO  = 3;
  TAX_ISENTO        = 4;
  TAX_ISS           = 5;

  // Antonio 2013 Dec 04 - Type of promo
  PROMO_COUPON_TYPE = 1;
  PROMO_FREQBUYER_TYPE = 2;
  PROMO_LOYALTY_TYPE = 3;
  PROMO_SALE_TYPE = 4;

  // Antonio 2013 Dec 05 - Type of discount to promo
  PROMO_DISCOUNT_AMOUNT = 1;
  PROMO_DISCOUNT_PERCENT = 2;
  PROMO_DISCOUNT_QTY = 3;
  PROMO_DISCOUNT_SALE = 4;

implementation

end.
