IF NOT EXISTS(select * from dbo.sysobjects 
	where id = object_id(N'[dbo].[vw_sis_chaveEstrangeira]'))
	 EXEC('
		CREATE VIEW vw_Sis_ChaveEstrangeira  AS
			SELECT 
			FC.TABLE_NAME AS TabelaDerivada,
			FC.COLUMN_NAME AS ChaveEstrangeira,
			DC.COLUMN_NAME AS ChaveOriginal,
			DC.TABLE_NAME AS TabelaOriginal,
			RC.CONSTRAINT_NAME AS ConstraintName
		FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE FC
		JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
			ON (FC.CONSTRAINT_NAME = RC.CONSTRAINT_NAME)
		JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE DC
			ON (RC.UNIQUE_CONSTRAINT_NAME = DC.CONSTRAINT_NAME)')
GO