ALTER TABLE SubGroup ADD CONSTRAINT
	DF_Zero1234 DEFAULT (0) FOR System
GO

ALTER TABLE SubGroup ADD CONSTRAINT
	DF_Zero1235 DEFAULT (0) FOR Hidden
GO

ALTER TABLE SubGroup ADD CONSTRAINT
	DF_Zero1236 DEFAULT (0) FOR Desativado
GO
