SET QUOTED_IDENTIFIER ON
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

SET ARITHABORT ON
GO

SET NUMERIC_ROUNDABORT OFF
GO

SET CONCAT_NULL_YIELDS_NULL ON
GO

SET ANSI_NULLS ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_WARNINGS ON
GO

CREATE TABLE dbo.Tmp_InvoiceGen
	(
	IDInvoice int NOT NULL,
	BitGen bit NULL
	)  ON [PRIMARY]
GO

IF EXISTS(SELECT * FROM dbo.InvoiceGen)
	 EXEC('INSERT INTO dbo.Tmp_InvoiceGen (IDInvoice, BitGen)
		SELECT IDInvoice, BitGen FROM dbo.InvoiceGen TABLOCKX')
GO

DROP TABLE dbo.InvoiceGen
GO

EXECUTE sp_rename N'dbo.Tmp_InvoiceGen', N'InvoiceGen', 'OBJECT'
GO

ALTER TABLE dbo.InvoiceGen ADD CONSTRAINT
	PK__InvoiceGen__0E04126B PRIMARY KEY CLUSTERED 
	(
	IDInvoice
	) ON [PRIMARY]

GO
