ALTER TABLE PreInventoryMov ADD
	Promo bit NULL CONSTRAINT DF_Zero2512 DEFAULT 0
GO

UPDATE PreInventoryMov SET Promo = 0
GO

ALTER TABLE InventoryMov DISABLE TRIGGER ALL
GO

ALTER TABLE InventoryMov ADD
	Promo bit NULL CONSTRAINT DF_Zero2519 DEFAULT 0
GO

UPDATE InventoryMov SET Promo = 0
GO

ALTER TABLE InventoryMov ENABLE TRIGGER ALL
GO
