ALTER TABLE InvoiceOBS ADD
       IDCFOP int NULL,
       IDPessoaTax int NULL
GO

ALTER TABLE InvoiceOBS ADD CONSTRAINT
	FK_Pessoa_InvoiceOBS_IDPessoaTax FOREIGN KEY (IDPessoaTax) REFERENCES Pessoa
GO

ALTER TABLE InvoiceOBS ADD CONSTRAINT
	FK_MntCFOP_InvoiceOBS_IDCFOP FOREIGN KEY (IDCFOP) REFERENCES Mnt_CFOP
GO

ALTER TABLE Invoice DROP CONSTRAINT FK_MntCFOP_Invoice_IDCFOP
GO

ALTER TABLE Invoice DROP COLUMN IDCFOP
GO
