IF NOT EXISTS (SELECT C.NAME FROM SYSCOLUMNS C WHERE C.ID = OBJECT_ID('MeioPag') AND C.NAME = 'FlatPenalty')
	ALTER TABLE MeioPag ADD FlatPenalty Boolean NULL
GO

IF NOT EXISTS (SELECT C.NAME FROM SYSCOLUMNS C WHERE C.ID = OBJECT_ID('MeioPag') AND C.NAME = 'PenaltyValue')
	ALTER TABLE MeioPag ADD PenaltyValue money NULL
GO

IF NOT EXISTS (SELECT C.NAME FROM SYSCOLUMNS C WHERE C.ID = OBJECT_ID('MeioPag') AND C.NAME = 'DailtInterest')
	ALTER TABLE MeioPag ADD DailtInterest money NULL
GO